[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "swarnabha", email = "swarnabhadutta909@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "groq>=1.7.0",
    "indic-nlp-library>=0.92",
    "onnxruntime>=1.29.0",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.0",
    "sacremoses>=0.2.0",
    "sentence-transformers>=6.0.1",
    "sentencepiece>=0.2.2",
    "transformers>=5.16.1",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
